version: "3.8"

services:
  backend:
    build: ./Inventory-Backend
    ports:
      - "8080:8080"

  frontend:
    build: ./Inventory-Frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
