version: "3.8"

services:
  backend:
    build: ./Inventory-Backend
    ports:
      - "8443:8443"
    volumes:
      - /opt/ssl:/opt/ssl:ro

  frontend:
    build: ./Inventory-Frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
